/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VereinRouteImport } from './routes/verein'
import { Route as TermineRouteImport } from './routes/termine'
import { Route as MitgliederRouteImport } from './routes/mitglieder'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as BootshausRouteImport } from './routes/bootshaus'
import { Route as AnmeldungRouteImport } from './routes/anmeldung'
import { Route as AktuellesRouteImport } from './routes/aktuelles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RudernWanderrudernRouteImport } from './routes/rudern.wanderrudern'
import { Route as RudernLeistungssportRouteImport } from './routes/rudern.leistungssport'
import { Route as RudernBreitensportRouteImport } from './routes/rudern.breitensport'
import { Route as RudernAnfaengerkurseRouteImport } from './routes/rudern.anfaengerkurse'

const VereinRoute = VereinRouteImport.update({
  id: '/verein',
  path: '/verein',
  getParentRoute: () => rootRouteImport,
} as any)
const TermineRoute = TermineRouteImport.update({
  id: '/termine',
  path: '/termine',
  getParentRoute: () => rootRouteImport,
} as any)
const MitgliederRoute = MitgliederRouteImport.update({
  id: '/mitglieder',
  path: '/mitglieder',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const BootshausRoute = BootshausRouteImport.update({
  id: '/bootshaus',
  path: '/bootshaus',
  getParentRoute: () => rootRouteImport,
} as any)
const AnmeldungRoute = AnmeldungRouteImport.update({
  id: '/anmeldung',
  path: '/anmeldung',
  getParentRoute: () => rootRouteImport,
} as any)
const AktuellesRoute = AktuellesRouteImport.update({
  id: '/aktuelles',
  path: '/aktuelles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RudernWanderrudernRoute = RudernWanderrudernRouteImport.update({
  id: '/rudern/wanderrudern',
  path: '/rudern/wanderrudern',
  getParentRoute: () => rootRouteImport,
} as any)
const RudernLeistungssportRoute = RudernLeistungssportRouteImport.update({
  id: '/rudern/leistungssport',
  path: '/rudern/leistungssport',
  getParentRoute: () => rootRouteImport,
} as any)
const RudernBreitensportRoute = RudernBreitensportRouteImport.update({
  id: '/rudern/breitensport',
  path: '/rudern/breitensport',
  getParentRoute: () => rootRouteImport,
} as any)
const RudernAnfaengerkurseRoute = RudernAnfaengerkurseRouteImport.update({
  id: '/rudern/anfaengerkurse',
  path: '/rudern/anfaengerkurse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aktuelles': typeof AktuellesRoute
  '/anmeldung': typeof AnmeldungRoute
  '/bootshaus': typeof BootshausRoute
  '/downloads': typeof DownloadsRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/mitglieder': typeof MitgliederRoute
  '/termine': typeof TermineRoute
  '/verein': typeof VereinRoute
  '/rudern/anfaengerkurse': typeof RudernAnfaengerkurseRoute
  '/rudern/breitensport': typeof RudernBreitensportRoute
  '/rudern/leistungssport': typeof RudernLeistungssportRoute
  '/rudern/wanderrudern': typeof RudernWanderrudernRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aktuelles': typeof AktuellesRoute
  '/anmeldung': typeof AnmeldungRoute
  '/bootshaus': typeof BootshausRoute
  '/downloads': typeof DownloadsRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/mitglieder': typeof MitgliederRoute
  '/termine': typeof TermineRoute
  '/verein': typeof VereinRoute
  '/rudern/anfaengerkurse': typeof RudernAnfaengerkurseRoute
  '/rudern/breitensport': typeof RudernBreitensportRoute
  '/rudern/leistungssport': typeof RudernLeistungssportRoute
  '/rudern/wanderrudern': typeof RudernWanderrudernRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aktuelles': typeof AktuellesRoute
  '/anmeldung': typeof AnmeldungRoute
  '/bootshaus': typeof BootshausRoute
  '/downloads': typeof DownloadsRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/mitglieder': typeof MitgliederRoute
  '/termine': typeof TermineRoute
  '/verein': typeof VereinRoute
  '/rudern/anfaengerkurse': typeof RudernAnfaengerkurseRoute
  '/rudern/breitensport': typeof RudernBreitensportRoute
  '/rudern/leistungssport': typeof RudernLeistungssportRoute
  '/rudern/wanderrudern': typeof RudernWanderrudernRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aktuelles'
    | '/anmeldung'
    | '/bootshaus'
    | '/downloads'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/mitglieder'
    | '/termine'
    | '/verein'
    | '/rudern/anfaengerkurse'
    | '/rudern/breitensport'
    | '/rudern/leistungssport'
    | '/rudern/wanderrudern'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aktuelles'
    | '/anmeldung'
    | '/bootshaus'
    | '/downloads'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/mitglieder'
    | '/termine'
    | '/verein'
    | '/rudern/anfaengerkurse'
    | '/rudern/breitensport'
    | '/rudern/leistungssport'
    | '/rudern/wanderrudern'
  id:
    | '__root__'
    | '/'
    | '/aktuelles'
    | '/anmeldung'
    | '/bootshaus'
    | '/downloads'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/mitglieder'
    | '/termine'
    | '/verein'
    | '/rudern/anfaengerkurse'
    | '/rudern/breitensport'
    | '/rudern/leistungssport'
    | '/rudern/wanderrudern'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AktuellesRoute: typeof AktuellesRoute
  AnmeldungRoute: typeof AnmeldungRoute
  BootshausRoute: typeof BootshausRoute
  DownloadsRoute: typeof DownloadsRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  MitgliederRoute: typeof MitgliederRoute
  TermineRoute: typeof TermineRoute
  VereinRoute: typeof VereinRoute
  RudernAnfaengerkurseRoute: typeof RudernAnfaengerkurseRoute
  RudernBreitensportRoute: typeof RudernBreitensportRoute
  RudernLeistungssportRoute: typeof RudernLeistungssportRoute
  RudernWanderrudernRoute: typeof RudernWanderrudernRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verein': {
      id: '/verein'
      path: '/verein'
      fullPath: '/verein'
      preLoaderRoute: typeof VereinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termine': {
      id: '/termine'
      path: '/termine'
      fullPath: '/termine'
      preLoaderRoute: typeof TermineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitglieder': {
      id: '/mitglieder'
      path: '/mitglieder'
      fullPath: '/mitglieder'
      preLoaderRoute: typeof MitgliederRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootshaus': {
      id: '/bootshaus'
      path: '/bootshaus'
      fullPath: '/bootshaus'
      preLoaderRoute: typeof BootshausRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anmeldung': {
      id: '/anmeldung'
      path: '/anmeldung'
      fullPath: '/anmeldung'
      preLoaderRoute: typeof AnmeldungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktuelles': {
      id: '/aktuelles'
      path: '/aktuelles'
      fullPath: '/aktuelles'
      preLoaderRoute: typeof AktuellesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rudern/wanderrudern': {
      id: '/rudern/wanderrudern'
      path: '/rudern/wanderrudern'
      fullPath: '/rudern/wanderrudern'
      preLoaderRoute: typeof RudernWanderrudernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rudern/leistungssport': {
      id: '/rudern/leistungssport'
      path: '/rudern/leistungssport'
      fullPath: '/rudern/leistungssport'
      preLoaderRoute: typeof RudernLeistungssportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rudern/breitensport': {
      id: '/rudern/breitensport'
      path: '/rudern/breitensport'
      fullPath: '/rudern/breitensport'
      preLoaderRoute: typeof RudernBreitensportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rudern/anfaengerkurse': {
      id: '/rudern/anfaengerkurse'
      path: '/rudern/anfaengerkurse'
      fullPath: '/rudern/anfaengerkurse'
      preLoaderRoute: typeof RudernAnfaengerkurseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AktuellesRoute: AktuellesRoute,
  AnmeldungRoute: AnmeldungRoute,
  BootshausRoute: BootshausRoute,
  DownloadsRoute: DownloadsRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  MitgliederRoute: MitgliederRoute,
  TermineRoute: TermineRoute,
  VereinRoute: VereinRoute,
  RudernAnfaengerkurseRoute: RudernAnfaengerkurseRoute,
  RudernBreitensportRoute: RudernBreitensportRoute,
  RudernLeistungssportRoute: RudernLeistungssportRoute,
  RudernWanderrudernRoute: RudernWanderrudernRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
